---
description: Tracks failed Duo Workflow executions
internal_events: true
action: request_duo_workflow_failure
product_group: duo_workflow
additional_properties:
  label:
    description: Workflow event type label
  property:
    description: Workflow failure reason
  value:
    description: Workflow Id that can be used to connect this event to others that happen when the workflow is completed.
milestone: '17.6'
introduced_by_url: https://gitlab.com/gitlab-org/duo-workflow/duo-workflow-service/-/merge_requests/153
distributions:
  - ee
tiers:
  - ultimate